[2024-06-04T17:58:42.792-0500] {processor.py:161} INFO - Started process (PID=23008) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:58:42.793-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:58:42.795-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:58:42.795-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:58:42.798-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:58:42.808-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.023 seconds
[2024-06-04T17:59:01.729-0500] {processor.py:161} INFO - Started process (PID=23029) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:01.731-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:01.734-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:01.733-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:01.738-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:01.756-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.038 seconds
[2024-06-04T17:59:04.997-0500] {processor.py:161} INFO - Started process (PID=23032) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:04.999-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:05.001-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:05.001-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:05.005-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:05.016-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.035 seconds
[2024-06-04T17:59:07.846-0500] {processor.py:161} INFO - Started process (PID=23038) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:07.848-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:07.851-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:07.850-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:07.856-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:07.855-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 18
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-06-04T17:59:07.857-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:07.878-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.050 seconds
[2024-06-04T17:59:10.770-0500] {processor.py:161} INFO - Started process (PID=23044) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:10.771-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:10.778-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:10.777-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:10.782-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:10.781-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 15
    default_args= = d
                  ^
SyntaxError: invalid syntax
[2024-06-04T17:59:10.782-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:10.809-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.047 seconds
[2024-06-04T17:59:20.113-0500] {processor.py:161} INFO - Started process (PID=23060) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:20.116-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:20.119-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:20.118-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:20.123-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:20.122-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 15
    default_args = def
                   ^^^
SyntaxError: invalid syntax
[2024-06-04T17:59:20.123-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:20.150-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.044 seconds
[2024-06-04T17:59:22.047-0500] {processor.py:161} INFO - Started process (PID=23066) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:22.048-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:22.050-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:22.049-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:22.056-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:22.055-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 15, in <module>
    default_args = defau
NameError: name 'defau' is not defined
[2024-06-04T17:59:22.057-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:22.091-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.057 seconds
[2024-06-04T17:59:25.771-0500] {processor.py:161} INFO - Started process (PID=23072) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:25.773-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:25.776-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:25.775-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:25.783-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:25.781-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 15, in <module>
    default_args = default_a
NameError: name 'default_a' is not defined
[2024-06-04T17:59:25.784-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:25.813-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.056 seconds
[2024-06-04T17:59:28.791-0500] {processor.py:161} INFO - Started process (PID=23083) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:28.794-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:28.798-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:28.797-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:28.806-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:28.830-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.057 seconds
[2024-06-04T17:59:30.143-0500] {processor.py:161} INFO - Started process (PID=23085) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:30.143-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:30.145-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:30.145-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:30.149-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:30.148-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 19
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-06-04T17:59:30.150-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:30.169-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.035 seconds
[2024-06-04T17:59:31.278-0500] {processor.py:161} INFO - Started process (PID=23090) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:31.279-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:31.280-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:31.280-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:31.283-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:31.282-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 19
    )
    ^
SyntaxError: invalid syntax
[2024-06-04T17:59:31.283-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:31.304-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.032 seconds
[2024-06-04T17:59:36.780-0500] {processor.py:161} INFO - Started process (PID=23096) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:36.781-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:36.783-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:36.783-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:36.786-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:36.785-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 19
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-06-04T17:59:36.786-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:36.811-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.037 seconds
[2024-06-04T17:59:37.963-0500] {processor.py:161} INFO - Started process (PID=23098) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:37.964-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:37.966-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:37.966-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:37.969-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:37.969-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 19
    )
    ^
SyntaxError: invalid syntax
[2024-06-04T17:59:37.970-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:37.990-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.035 seconds
[2024-06-04T17:59:45.242-0500] {processor.py:161} INFO - Started process (PID=23103) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:45.243-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:45.246-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:45.245-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:45.251-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:45.249-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2024-06-04T17:59:45.251-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:45.279-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.058 seconds
[2024-06-04T17:59:48.094-0500] {processor.py:161} INFO - Started process (PID=23111) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:48.095-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:48.097-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:48.097-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:48.101-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:48.100-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    sta
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T17:59:48.101-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:48.124-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.036 seconds
[2024-06-04T17:59:49.256-0500] {processor.py:161} INFO - Started process (PID=23113) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:49.257-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:49.259-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:49.258-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:49.262-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:49.261-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 17
    schedule_interval=
                     ^
SyntaxError: invalid syntax
[2024-06-04T17:59:49.262-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:49.285-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.036 seconds
[2024-06-04T17:59:56.028-0500] {processor.py:161} INFO - Started process (PID=23124) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:56.031-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:56.033-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:56.032-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:56.036-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:56.035-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 17
    schedule_interval=
                     ^
SyntaxError: invalid syntax
[2024-06-04T17:59:56.037-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:56.056-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.039 seconds
[2024-06-04T17:59:59.202-0500] {processor.py:161} INFO - Started process (PID=23133) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:59.203-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T17:59:59.205-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:59.204-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:59.208-0500] {logging_mixin.py:188} INFO - [2024-06-04T17:59:59.207-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 17
    schedule_interval=
                     ^
SyntaxError: invalid syntax
[2024-06-04T17:59:59.209-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T17:59:59.231-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.034 seconds
[2024-06-04T18:00:00.377-0500] {processor.py:161} INFO - Started process (PID=23135) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:00.379-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:00.381-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:00.381-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:00.386-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:00.385-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 17
    schedule_interval=
                     ^
SyntaxError: invalid syntax
[2024-06-04T18:00:00.386-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:00.409-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.043 seconds
[2024-06-04T18:00:02.591-0500] {processor.py:161} INFO - Started process (PID=23142) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:02.593-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:02.595-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:02.595-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:02.601-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:02.600-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  da
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:02.602-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:02.627-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.053 seconds
[2024-06-04T18:00:07.239-0500] {processor.py:161} INFO - Started process (PID=23149) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:07.240-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:07.243-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:07.242-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:07.246-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:07.245-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:07.247-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:07.270-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.043 seconds
[2024-06-04T18:00:12.157-0500] {processor.py:161} INFO - Started process (PID=23155) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:12.157-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:12.159-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:12.159-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:12.163-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:12.162-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:12.163-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:12.183-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.032 seconds
[2024-06-04T18:00:14.066-0500] {processor.py:161} INFO - Started process (PID=23159) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:14.067-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:14.070-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:14.069-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:14.073-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:14.072-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:14.073-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:14.092-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.034 seconds
[2024-06-04T18:00:15.430-0500] {processor.py:161} INFO - Started process (PID=23161) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:15.432-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:15.434-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:15.434-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:15.438-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:15.437-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:15.439-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:15.462-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.048 seconds
[2024-06-04T18:00:17.318-0500] {processor.py:161} INFO - Started process (PID=23164) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:17.319-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:17.322-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:17.321-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:17.325-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:17.324-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:17.325-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:17.349-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.041 seconds
[2024-06-04T18:00:19.163-0500] {processor.py:161} INFO - Started process (PID=23166) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:19.164-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:19.166-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:19.165-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:19.169-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:19.168-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:19.169-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:19.188-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.036 seconds
[2024-06-04T18:00:27.980-0500] {processor.py:161} INFO - Started process (PID=23179) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:27.984-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:27.986-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:27.986-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:27.990-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:27.989-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:27.991-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:28.017-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.045 seconds
[2024-06-04T18:00:29.416-0500] {processor.py:161} INFO - Started process (PID=23186) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:29.417-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:29.419-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:29.419-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:29.423-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:29.422-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:29.424-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:29.452-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.045 seconds
[2024-06-04T18:00:30.627-0500] {processor.py:161} INFO - Started process (PID=23189) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:30.629-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:30.634-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:30.633-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:30.640-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:30.639-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:30.641-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:30.675-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.077 seconds
[2024-06-04T18:00:32.807-0500] {processor.py:161} INFO - Started process (PID=23193) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:32.809-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:32.812-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:32.810-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:32.816-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:32.815-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:32.817-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:32.848-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.050 seconds
[2024-06-04T18:00:33.920-0500] {processor.py:161} INFO - Started process (PID=23195) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:33.920-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:33.922-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:33.922-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:33.925-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:33.924-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:33.925-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:33.944-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.031 seconds
[2024-06-04T18:00:41.236-0500] {processor.py:161} INFO - Started process (PID=23206) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:41.237-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:41.239-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:41.238-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:41.243-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:41.242-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:41.243-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:41.270-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.041 seconds
[2024-06-04T18:00:43.209-0500] {processor.py:161} INFO - Started process (PID=23209) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:43.210-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:43.217-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:43.216-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:43.221-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:43.219-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:43.222-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:43.248-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.047 seconds
[2024-06-04T18:00:47.036-0500] {processor.py:161} INFO - Started process (PID=23213) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:47.036-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:47.038-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:47.037-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:47.040-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:47.040-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:47.041-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:47.059-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.030 seconds
[2024-06-04T18:00:49.300-0500] {processor.py:161} INFO - Started process (PID=23215) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:49.302-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:49.306-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:49.305-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:49.311-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:49.310-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:49.312-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:49.341-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.064 seconds
[2024-06-04T18:00:51.465-0500] {processor.py:161} INFO - Started process (PID=23221) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:51.466-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:51.469-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:51.468-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:51.472-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:51.471-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:51.473-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:51.495-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.038 seconds
[2024-06-04T18:00:54.451-0500] {processor.py:161} INFO - Started process (PID=23223) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:54.452-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:54.454-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:54.453-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:54.458-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:54.457-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:54.458-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:54.479-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.038 seconds
[2024-06-04T18:00:58.982-0500] {processor.py:161} INFO - Started process (PID=23234) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:58.984-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:00:58.987-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:58.986-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:58.991-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:00:58.990-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:00:58.992-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:00:59.012-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.045 seconds
[2024-06-04T18:01:03.292-0500] {processor.py:161} INFO - Started process (PID=23245) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:03.293-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:01:03.295-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:03.295-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:03.298-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:03.298-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:01:03.299-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:03.323-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.037 seconds
[2024-06-04T18:01:04.442-0500] {processor.py:161} INFO - Started process (PID=23247) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:04.443-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:01:04.445-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:04.444-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:04.448-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:04.447-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:01:04.448-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:04.470-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.035 seconds
[2024-06-04T18:01:06.265-0500] {processor.py:161} INFO - Started process (PID=23249) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:06.266-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:01:06.268-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:06.268-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:06.273-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:06.271-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:01:06.274-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:06.298-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.045 seconds
[2024-06-04T18:01:07.951-0500] {processor.py:161} INFO - Started process (PID=23254) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:07.953-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:01:07.956-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:07.955-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:07.960-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:07.959-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:01:07.961-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:07.987-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.048 seconds
[2024-06-04T18:01:09.129-0500] {processor.py:161} INFO - Started process (PID=23256) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:09.130-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:01:09.133-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:09.132-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:09.136-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:09.135-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:01:09.136-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:09.157-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.038 seconds
[2024-06-04T18:01:12.331-0500] {processor.py:161} INFO - Started process (PID=23259) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:12.332-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:01:12.333-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:12.333-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:12.337-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:12.336-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:01:12.337-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:12.356-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.032 seconds
[2024-06-04T18:01:39.995-0500] {processor.py:161} INFO - Started process (PID=23300) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:40.001-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:01:40.007-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:40.006-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:40.015-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:40.014-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:01:40.016-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:40.047-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.082 seconds
[2024-06-04T18:01:48.986-0500] {processor.py:161} INFO - Started process (PID=23309) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:48.990-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:01:48.996-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:48.994-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:49.006-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:49.004-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:01:49.007-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:49.036-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.080 seconds
[2024-06-04T18:01:52.275-0500] {processor.py:161} INFO - Started process (PID=23311) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:52.276-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:01:52.279-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:52.279-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:52.283-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:52.282-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 14
    dag_id = 'dag_with_task_flow',
IndentationError: unexpected indent
[2024-06-04T18:01:52.284-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:52.306-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.049 seconds
[2024-06-04T18:01:55.531-0500] {processor.py:161} INFO - Started process (PID=23318) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:55.536-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:01:55.542-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:55.540-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:55.553-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:01:55.551-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:01:55.554-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:01:55.596-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.092 seconds
[2024-06-04T18:02:10.708-0500] {processor.py:161} INFO - Started process (PID=23359) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:02:10.709-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:02:10.711-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:02:10.711-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:02:10.715-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:02:10.714-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:02:10.716-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:02:10.739-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.040 seconds
[2024-06-04T18:02:38.605-0500] {processor.py:161} INFO - Started process (PID=23390) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:02:38.610-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:02:38.617-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:02:38.615-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:02:38.628-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:02:38.626-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    start_date =  days_ago(1)
                  ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:02:38.630-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:02:38.690-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.106 seconds
[2024-06-04T18:02:46.580-0500] {processor.py:161} INFO - Started process (PID=23399) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:02:46.581-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:02:46.583-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:02:46.582-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:02:46.586-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:02:46.603-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.029 seconds
[2024-06-04T18:02:57.669-0500] {processor.py:161} INFO - Started process (PID=23408) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:02:57.670-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:02:57.672-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:02:57.672-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:02:57.676-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:02:57.686-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.026 seconds
[2024-06-04T18:02:59.909-0500] {processor.py:161} INFO - Started process (PID=23410) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:02:59.912-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:02:59.919-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:02:59.917-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:02:59.932-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:02:59.929-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 15
    des
    ^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:02:59.933-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:02:59.969-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.081 seconds
[2024-06-04T18:03:02.249-0500] {processor.py:161} INFO - Started process (PID=23423) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:02.250-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:03:02.251-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:02.251-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:02.254-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:02.254-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    default_args = default_args,
                 ^
SyntaxError: invalid syntax
[2024-06-04T18:03:02.255-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:02.281-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.039 seconds
[2024-06-04T18:03:04.300-0500] {processor.py:161} INFO - Started process (PID=23453) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:04.302-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:03:04.304-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:04.303-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:04.309-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:04.308-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    default_args = default_args,
                 ^
SyntaxError: invalid syntax
[2024-06-04T18:03:04.310-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:04.339-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.049 seconds
[2024-06-04T18:03:05.475-0500] {processor.py:161} INFO - Started process (PID=23455) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:05.476-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:03:05.478-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:05.478-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:05.483-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:05.482-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 16
    default_args = default_args,
                 ^
SyntaxError: invalid syntax
[2024-06-04T18:03:05.484-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:05.506-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.040 seconds
[2024-06-04T18:03:06.654-0500] {processor.py:161} INFO - Started process (PID=23461) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:06.656-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:03:06.659-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:06.658-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:06.663-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:06.662-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 15
    description = ''
                  
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:03:06.663-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:06.685-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.044 seconds
[2024-06-04T18:03:16.553-0500] {processor.py:161} INFO - Started process (PID=23467) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:16.557-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:03:16.558-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:16.558-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:16.561-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:16.560-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 15
    description = 'My first '
                  
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:03:16.561-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:16.582-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.036 seconds
[2024-06-04T18:03:18.319-0500] {processor.py:161} INFO - Started process (PID=23471) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:18.322-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:03:18.329-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:18.327-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:18.340-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:18.337-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 15
    description = 'My first dag usi'
                  
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:03:18.341-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:18.372-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.078 seconds
[2024-06-04T18:03:22.410-0500] {processor.py:161} INFO - Started process (PID=23476) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:22.412-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:03:22.415-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:22.414-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:22.420-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:22.419-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 15
    description = 'My first dag using task flro'
                  
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:03:22.421-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:22.447-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.054 seconds
[2024-06-04T18:03:26.657-0500] {processor.py:161} INFO - Started process (PID=23477) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:26.659-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:03:26.665-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:26.663-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:26.672-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:26.670-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 15
    description = 'My first dag using task flow ap'
                  
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:03:26.673-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:26.700-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.068 seconds
[2024-06-04T18:03:28.495-0500] {processor.py:161} INFO - Started process (PID=23484) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:28.496-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:03:28.497-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:28.497-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:28.500-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:28.499-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 15
    description = 'My first dag using task flow api'
                  
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-04T18:03:28.500-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:28.522-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.033 seconds
[2024-06-04T18:03:33.478-0500] {processor.py:161} INFO - Started process (PID=23493) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:33.481-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:03:33.491-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:33.489-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:33.502-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:33.545-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.085 seconds
[2024-06-04T18:03:35.367-0500] {processor.py:161} INFO - Started process (PID=23499) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:35.368-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:03:35.369-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:03:35.369-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:35.372-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:03:35.463-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.105 seconds
[2024-06-04T18:04:06.359-0500] {processor.py:161} INFO - Started process (PID=23531) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:04:06.364-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:04:06.367-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:04:06.366-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:04:06.372-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:04:06.384-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.043 seconds
[2024-06-04T18:04:37.424-0500] {processor.py:161} INFO - Started process (PID=23584) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:04:37.425-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:04:37.428-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:04:37.427-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:04:37.431-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:04:37.447-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.033 seconds
[2024-06-04T18:04:57.726-0500] {processor.py:161} INFO - Started process (PID=23600) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:04:57.730-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:04:57.732-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:04:57.731-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:04:57.740-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:04:57.847-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:04:57.846-0500] {override.py:1829} INFO - Created Permission View: can delete on DAG:dag_with_task_flow
[2024-06-04T18:04:57.860-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:04:57.860-0500] {override.py:1829} INFO - Created Permission View: can edit on DAG:dag_with_task_flow
[2024-06-04T18:04:57.870-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:04:57.870-0500] {override.py:1829} INFO - Created Permission View: can read on DAG:dag_with_task_flow
[2024-06-04T18:04:57.871-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:04:57.870-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:04:57.886-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:04:57.885-0500] {dag.py:3118} INFO - Creating ORM DAG for dag_with_task_flow
[2024-06-04T18:04:57.895-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:04:57.895-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to 2024-06-03 00:00:00+00:00, run_after=2024-06-03 00:00:00+00:00
[2024-06-04T18:04:57.927-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.215 seconds
[2024-06-04T18:05:01.227-0500] {processor.py:161} INFO - Started process (PID=23602) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:01.228-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:05:01.231-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:01.230-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:01.241-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:01.250-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:01.249-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:05:01.272-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:01.272-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to 2024-06-03 00:00:00+00:00, run_after=2024-06-03 00:00:00+00:00
[2024-06-04T18:05:01.306-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.096 seconds
[2024-06-04T18:05:31.920-0500] {processor.py:161} INFO - Started process (PID=23627) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:31.924-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:05:31.926-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:31.926-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:31.935-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:31.958-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:31.957-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:05:31.998-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:31.998-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to 2024-06-03 00:00:00+00:00, run_after=2024-06-03 00:00:00+00:00
[2024-06-04T18:05:32.044-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.135 seconds
[2024-06-04T18:05:33.816-0500] {processor.py:161} INFO - Started process (PID=23631) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:33.816-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:05:33.818-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:33.818-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:33.822-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:33.821-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 25
    dag_with_task_flow()
IndentationError: unexpected unindent
[2024-06-04T18:05:33.822-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:33.846-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.037 seconds
[2024-06-04T18:05:36.240-0500] {processor.py:161} INFO - Started process (PID=23636) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:36.245-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:05:36.252-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:36.250-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:36.265-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:36.262-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 23
    def
       ^
SyntaxError: invalid syntax
[2024-06-04T18:05:36.267-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:36.331-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.115 seconds
[2024-06-04T18:05:39.313-0500] {processor.py:161} INFO - Started process (PID=23646) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:39.315-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:05:39.321-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:39.319-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:39.331-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:39.329-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 23
    def print
             ^
SyntaxError: invalid syntax
[2024-06-04T18:05:39.332-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:39.384-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.094 seconds
[2024-06-04T18:05:41.679-0500] {processor.py:161} INFO - Started process (PID=23650) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:41.680-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:05:41.682-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:41.682-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:41.686-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:41.685-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 23
    def print()
               ^
SyntaxError: expected ':'
[2024-06-04T18:05:41.687-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:41.707-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.039 seconds
[2024-06-04T18:05:44.756-0500] {processor.py:161} INFO - Started process (PID=23656) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:44.759-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:05:44.765-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:44.764-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:44.772-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:44.770-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 23
    def print("fir")
              ^^^^^
SyntaxError: invalid syntax
[2024-06-04T18:05:44.773-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:44.808-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.086 seconds
[2024-06-04T18:05:46.302-0500] {processor.py:161} INFO - Started process (PID=23658) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:46.304-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:05:46.310-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:46.309-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:46.324-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:46.321-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 23
    def print("first ")
              ^^^^^^^^
SyntaxError: invalid syntax
[2024-06-04T18:05:46.325-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:46.367-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.089 seconds
[2024-06-04T18:05:51.356-0500] {processor.py:161} INFO - Started process (PID=23664) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:51.359-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:05:51.366-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:51.364-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:51.381-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:51.378-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 23
    def print()
               ^
SyntaxError: expected ':'
[2024-06-04T18:05:51.383-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:51.433-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.106 seconds
[2024-06-04T18:05:58.445-0500] {processor.py:161} INFO - Started process (PID=23673) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:58.449-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:05:58.452-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:58.451-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:58.458-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:05:58.457-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 23
    def ()
        ^
SyntaxError: invalid syntax
[2024-06-04T18:05:58.459-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:05:58.482-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.054 seconds
[2024-06-04T18:06:00.641-0500] {processor.py:161} INFO - Started process (PID=23678) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:00.643-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:06:00.645-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:00.644-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:00.650-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:00.649-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 23
    def ats()
             ^
SyntaxError: expected ':'
[2024-06-04T18:06:00.651-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:00.683-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.050 seconds
[2024-06-04T18:06:03.643-0500] {processor.py:161} INFO - Started process (PID=23683) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:03.647-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:06:03.653-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:03.652-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:03.665-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:03.664-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 23
    def task()
              ^
SyntaxError: expected ':'
[2024-06-04T18:06:03.666-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:03.698-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.079 seconds
[2024-06-04T18:06:06.867-0500] {processor.py:161} INFO - Started process (PID=23691) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:06.870-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:06:06.874-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:06.873-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:06.878-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:06.877-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 23
    def task_a()
                ^
SyntaxError: expected ':'
[2024-06-04T18:06:06.878-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:06.899-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.038 seconds
[2024-06-04T18:06:08.074-0500] {processor.py:161} INFO - Started process (PID=23692) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:08.075-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:06:08.078-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:08.077-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:08.083-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:08.082-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 27
    dag_with_task_flow()
IndentationError: expected an indented block after function definition on line 23
[2024-06-04T18:06:08.084-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:08.117-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.057 seconds
[2024-06-04T18:06:12.628-0500] {processor.py:161} INFO - Started process (PID=23703) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:12.632-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:06:12.635-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:12.634-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:12.644-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:12.657-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:12.657-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:06:12.675-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:12.675-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to 2024-06-03 00:00:00+00:00, run_after=2024-06-03 00:00:00+00:00
[2024-06-04T18:06:12.714-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.101 seconds
[2024-06-04T18:06:13.894-0500] {processor.py:161} INFO - Started process (PID=23708) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:13.896-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:06:13.898-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:13.898-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:13.911-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:13.929-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:13.929-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:06:13.956-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:13.956-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to 2024-06-03 00:00:00+00:00, run_after=2024-06-03 00:00:00+00:00
[2024-06-04T18:06:14.009-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.125 seconds
[2024-06-04T18:06:17.958-0500] {processor.py:161} INFO - Started process (PID=23710) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:17.960-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:06:17.963-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:17.962-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:17.978-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:17.999-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:17.999-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:06:18.028-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:18.028-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to 2024-06-03 00:00:00+00:00, run_after=2024-06-03 00:00:00+00:00
[2024-06-04T18:06:18.070-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.126 seconds
[2024-06-04T18:06:28.045-0500] {processor.py:161} INFO - Started process (PID=23728) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:28.047-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:06:28.049-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:28.048-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:28.059-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:28.078-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:28.078-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:06:28.110-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:28.110-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to 2024-06-03 00:00:00+00:00, run_after=2024-06-03 00:00:00+00:00
[2024-06-04T18:06:28.154-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.118 seconds
[2024-06-04T18:06:30.782-0500] {processor.py:161} INFO - Started process (PID=23733) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:30.783-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:06:30.785-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:30.785-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:30.793-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:30.809-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:30.809-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:06:30.829-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:30.828-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to 2024-06-03 00:00:00+00:00, run_after=2024-06-03 00:00:00+00:00
[2024-06-04T18:06:30.853-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.078 seconds
[2024-06-04T18:06:32.015-0500] {processor.py:161} INFO - Started process (PID=23735) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:32.017-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:06:32.020-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:32.020-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:32.033-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:32.062-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:32.062-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:06:32.102-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:32.102-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to 2024-06-03 00:00:00+00:00, run_after=2024-06-03 00:00:00+00:00
[2024-06-04T18:06:32.151-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.152 seconds
[2024-06-04T18:06:42.356-0500] {processor.py:161} INFO - Started process (PID=23751) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:42.357-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:06:42.360-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:42.360-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:42.371-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:42.384-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:42.384-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:06:42.403-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:42.402-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to 2024-06-03 00:00:00+00:00, run_after=2024-06-03 00:00:00+00:00
[2024-06-04T18:06:42.427-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.086 seconds
[2024-06-04T18:06:47.441-0500] {processor.py:161} INFO - Started process (PID=23758) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:47.445-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:06:47.451-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:47.449-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:47.466-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:47.463-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 27, in <module>
    task_
NameError: name 'task_' is not defined
[2024-06-04T18:06:47.468-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:47.502-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.069 seconds
[2024-06-04T18:06:48.661-0500] {processor.py:161} INFO - Started process (PID=23761) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:48.663-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:06:48.668-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:48.667-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:48.678-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:48.675-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 27, in <module>
    task_a
NameError: name 'task_a' is not defined
[2024-06-04T18:06:48.679-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:48.718-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.086 seconds
[2024-06-04T18:06:49.802-0500] {processor.py:161} INFO - Started process (PID=23767) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:49.803-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:06:49.806-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:49.805-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:49.811-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:49.810-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 27, in <module>
    task_a
NameError: name 'task_a' is not defined
[2024-06-04T18:06:49.812-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:49.834-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.042 seconds
[2024-06-04T18:06:57.494-0500] {processor.py:161} INFO - Started process (PID=23773) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:57.495-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:06:57.497-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:57.497-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:57.502-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:57.501-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 29, in <module>
    task_a
NameError: name 'task_a' is not defined
[2024-06-04T18:06:57.503-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:57.528-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.043 seconds
[2024-06-04T18:06:58.691-0500] {processor.py:161} INFO - Started process (PID=23775) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:58.693-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:06:58.698-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:58.697-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:58.710-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:06:58.708-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/build_dag_with_taskflow.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/diallo/airflow/dags/build_dag_with_taskflow.py", line 29, in <module>
    task_a
NameError: name 'task_a' is not defined
[2024-06-04T18:06:58.711-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:06:58.737-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.067 seconds
[2024-06-04T18:07:03.756-0500] {processor.py:161} INFO - Started process (PID=23782) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:07:03.759-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:07:03.764-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:07:03.762-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:07:03.781-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:07:03.800-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:07:03.800-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:07:03.819-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:07:03.818-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to 2024-06-03 00:00:00+00:00, run_after=2024-06-03 00:00:00+00:00
[2024-06-04T18:07:03.860-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.124 seconds
[2024-06-04T18:07:05.620-0500] {processor.py:161} INFO - Started process (PID=23787) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:07:05.624-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:07:05.631-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:07:05.629-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:07:05.659-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:07:05.680-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:07:05.680-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:07:05.702-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:07:05.701-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to 2024-06-03 00:00:00+00:00, run_after=2024-06-03 00:00:00+00:00
[2024-06-04T18:07:05.727-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.142 seconds
[2024-06-04T18:07:36.044-0500] {processor.py:161} INFO - Started process (PID=23863) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:07:36.047-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:07:36.049-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:07:36.049-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:07:36.059-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:07:36.081-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:07:36.080-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:07:36.109-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:07:36.108-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to 2024-06-03 00:00:00+00:00, run_after=2024-06-03 00:00:00+00:00
[2024-06-04T18:07:36.148-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.118 seconds
[2024-06-04T18:07:40.756-0500] {processor.py:161} INFO - Started process (PID=23875) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:07:40.756-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:07:40.758-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:07:40.758-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:07:40.766-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:07:40.864-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:07:40.864-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:07:40.880-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:07:40.880-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to 2024-06-03 00:00:00+00:00, run_after=2024-06-03 00:00:00+00:00
[2024-06-04T18:07:40.907-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.158 seconds
[2024-06-04T18:08:11.378-0500] {processor.py:161} INFO - Started process (PID=23927) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:08:11.381-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:08:11.383-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:08:11.383-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:08:11.392-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:08:11.414-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:08:11.414-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:08:11.434-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:08:11.433-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to 2024-06-03 00:00:00+00:00, run_after=2024-06-03 00:00:00+00:00
[2024-06-04T18:08:11.466-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.099 seconds
[2024-06-04T18:08:42.055-0500] {processor.py:161} INFO - Started process (PID=23955) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:08:42.056-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:08:42.058-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:08:42.058-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:08:42.076-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:08:42.108-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:08:42.108-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:08:42.144-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:08:42.143-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to 2024-06-03 00:00:00+00:00, run_after=2024-06-03 00:00:00+00:00
[2024-06-04T18:08:42.174-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.135 seconds
[2024-06-04T18:09:13.123-0500] {processor.py:161} INFO - Started process (PID=24047) to work on /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:09:13.126-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/build_dag_with_taskflow.py for tasks to queue
[2024-06-04T18:09:13.128-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:09:13.127-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:09:13.135-0500] {processor.py:840} INFO - DAG(s) 'dag_with_task_flow' retrieved from /home/diallo/airflow/dags/build_dag_with_taskflow.py
[2024-06-04T18:09:13.156-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:09:13.156-0500] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-04T18:09:13.174-0500] {logging_mixin.py:188} INFO - [2024-06-04T18:09:13.174-0500] {dag.py:3954} INFO - Setting next_dagrun for dag_with_task_flow to None, run_after=None
[2024-06-04T18:09:13.216-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/build_dag_with_taskflow.py took 0.099 seconds
